name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-linux:
    name: Build & Test (Ubuntu)
    runs-on: ubuntu-latest

    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 4
      CTEST_OUTPUT_ON_FAILURE: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build ccache

      - name: Install lcov
        run: |
          curl -L https://github.com/linux-test-project/lcov/releases/latest/download/lcov.tar.gz -o lcov.tar.gz
          tar -xzf lcov.tar.gz
          cd lcov-*
          make install PREFIX=$HOME/.local
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure (Debug)
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build
        run: cmake --build build -- -v

      - name: Test
        run: ctest --test-dir build --output-on-failure

      - name: Upload test logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: |
            build/Testing/Temporary/LastTest.log
            build/**/*.log
            build/**/*.xml
