name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build

      - name: Configure (Release)
        run: |
          cmake -S . -B build-rel -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build-rel --config Release

      - name: Package (tar.gz)
        run: |
          mkdir -p dist
          tar -C build-rel -czf dist/aiquant-linux-x86_64.tar.gz .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
